### ISSUE TITLE
Refactoring extract plain strings to variables

### ISSUE THREAD

**Issue by kevinwallimann** [AbsaOSS/hyperdrive-trigger#177] opened 2020-05-26 13:46 UTC
Extract plain strings in `SparkParameters` and `ShellParameters` to variables and reuse them.

E.g. `"mainClass"`, `"deploymentMode"` are hard-coded in many tests. Moreover it's impossible to navigate to the origin in the IDE. You have to do a full-text search instead.

**Comment by jozefbakus** [comment] 2021-04-12 11:19
Duplicate of #422

**Comment by jozefbakus** [comment] 2021-04-12 11:20
Duplicate of #422

**Closed as completed by jozefbakus** 2021-04-12 11:20 UTC
Labels: priority: medium, refactoring, backend
